---
title: "exercise1"
author: "Spencer Lee"
date: "2022-12-08"
output: github_document 
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(janeaustenr)
library(tidytext)
library(ggplot2)
```

## Background
Using the janeaustenr package and Emma book, we will be counting the number of words, and plotting the frequency of the most common words in bar chart using ggplot2. We will also remove stop words using the tidytext, stop_words() function.

```{r}
# Using the Jane Austen book collection
# Create tibble and convert to one text per row
book <- austen_books() %>%
    group_by(book) %>%
    mutate(line = row_number()) %>%
    ungroup()
book

book_tidied <- book %>%
    unnest_tokens(word, text)
book_tidied

# Removing stopwords from book tibble
rmstop_book <- book_tidied %>%
    anti_join(get_stopwords())

# Counting number of words in book
count_word <- rmstop_book %>%
    count(word, sort = T)
count_word



# Bar chart of top 15 most common stop words
count_word_plot_t <- count_word[1:15, ]
count_word_plot_t

# Plotting 15 most common words
plot_word <- ggplot(count_word_plot_t, aes(x = word, y = n)) +
    geom_col() +
    ylab("Frequency") +
    ggtitle("Most common words in Jane Austen books")
plot_word

```

## Including Plots


```{r}

```

